import { FlowConfiguration } from "@/modules/flow/types";

export * from "./nodeDimensions";

export const menuVariants = {
  initial: {
    scale: 0.95,
    opacity: 0,
    x: 0,
  },
  animate: {
    scale: 1,
    opacity: 1,
    x: 0,
  },
  exit: {
    scale: 0.95,
    opacity: 0,
    x: 0,
  },
};

export const tabVariants = {
  hidden: { opacity: 0, x: 20 },
  visible: { opacity: 1, x: 0 },
};

export const initialConfig = {
  project_name: "playground",
  config: {
    name: "Sample Config",
    version: "1.0",
    desciption: "",
    parameters: {
      nodes: [
        {
          id: "node_1",
          type: "start",
          label: "Start",
          position: { x: 515, y: 225 },
          data: {
            title: "Start",
            name: "start",
            type: "start",
            subtitle: "Start node",
            description: "Start of the orchestration",
            label: "Start",
            after_node_execution: "continue",
            inputs: [],
            outputs: [],
            triggers: [],
            sourceHandleConnected: { b: 1 },
          },
          zIndex: 2,
        },
        {
          id: "node_2",
          type: "end",
          label: "End",
          position: { x: 940, y: 225 },
          data: {
            name: "end",
            type: "end",
            title: "End",
            subtitle: "End node",
            label: "End",
            save_result: false,
            description: "End of the orchestration",
            after_node_execution: "continue",
            inputs: [],
            outputs: [],
            targetHandleConnected: { a: 1 },
          },
          zIndex: 2,
        },
      ],
      edges: [
        {
          animated: false,
          type: "curved",
          source: "node_1",
          sourceHandle: "b",
          target: "node_2",
          targetHandle: "a",
          id: "node_1-node_2-b-a",
          zIndex: 1,
          data: {
            targetNodeType: "end",
            isRuleEdge: false,
            showEdgeMenuPlus: true,
          },
        },
      ],
      pydanticModels: {
        id: 0,
        label: "Response format models",
        render_type: "code",
        type: { label: "List", value: "list" },
        language: { label: "YAML", value: "yaml" },
        value: "",
      },
    },
  },
};

export const AgentTemplates = {
  start: {
    id: "b1e7f2a8-1e7b-4e2e-9a7d-1f2e3c4b5a6d",
    type: "start",
    data: {
      name: "start",
      type: "start",
      title: "Start",
      subtitle: "Start Node Operator",
      description: "",
      label: "Start",
      save_result: false,
      after_node_execution: "continue",
      inputs: [],
      outputs: [],
      triggers: [],
    },
  },
  end: {
    id: "e2c9d3b4-5f6a-4b7c-8d9e-2a3b4c5d6e7f",
    type: "end",
    data: {
      name: "end",
      type: "end",
      title: "End",
      subtitle: "End of the orchestration",
      label: "End",
      save_result: false,
      description: "",
      after_node_execution: "continue",
      inputs: [],
      outputs: [],
    },
  },
  identity: {
    id: "f3a4b5c6-7d8e-4f9a-0b1c-2d3e4f5a6b7c",
    type: "identity",
    data: {
      name: "identity",
      type: "identity",
      title: "Create Parameter",
      subtitle: "Create Parameter, what you see what you get.",
      description: "Identity agent Passes data through unchanged",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: [],
      outputs: [],
    },
  },
  regexBinaryClassifier: {
    id: "c4b5a6d7-8e9f-4a1b-2c3d-4e5f6a7b8c9d",
    type: "agent",
    data: {
      name: "regexBinaryClassifier",
      type: "agent",
      title: "Regex Binary Classifier",
      subtitle: "Classifies if the input text some regex patterns",
      label: "",
      save_result: false,
      description: "Regex binary Classifier-Yes/no text classifier",
      after_node_execution: "continue",
      inputs: {
        data: "",
        regex_patterns: [],
        unwanted_regex_patterns: [],
        relevant_match: "Any",
        context_range: 1,
      },

      outputs: [
        {
          key: "Classification",
          id: "classification",
          type: "String",
        },
      ],
    },
  },
  regexMultiLabelClassifier: {
    id: "d5e6f7a8-9b0c-4d1e-2f3a-4b5c6d7e8f9a",
    type: "agent",
    data: {
      type: "agent",
      name: "regexMultiLabelClassifier",
      title: "Regex Multi Label Classifier",
      subtitle: "Multi-label classification using regular expressions.",
      description: "Regex multi label classifier Classify text using regex into related classes",
      save_result: false,
      after_node_execution: "continue",
      inputs: [],
      outputs: [
        {
          id: "labels",
          key: "Labels",
          type: "List",
        },
      ],
    },
  } as any,
  regexMultiClassClassifier: {
    id: "e6f7a8b9-0c1d-4e2f-3a4b-5c6d7e8f9a0a",
    type: "agent",
    data: {
      type: "agent",
      name: "regexMultiClassClassifier",
      title: "Regex Multi Class Classifier",
      subtitle: "Multi-class classification using regular expressions.",
      description: "Regex multi class classifier Classify text using regex patterns",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        iterable: {
          id: "2049d78b-55a0-41aa-aed7-5d9eddace715",
          key: "text",
          value: {
            label: "",
            value: "",
          },
          type: "String",
        },
        classes: [],
      },
      outputs: [
        {
          id: "classification",
          key: "Classification",
          type: "String",
        },
      ],
    },
  } as any,
  regexClusteringAgent: {
    id: "e6f7a8b9-0c1d-4e2f-3a4b-5c6d7e8f9a0b",
    type: "agent",
    data: {
      type: "agent",
      name: "regexClusteringAgent",
      title: "Regex Clustering",
      subtitle: "Clusters input data based on regex patterns",
      description: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        iterable: {
          id: "2049d78b-55a0-41aa-aed7-5d9eddace716",
          key: "iterable",
          value: {
            label: "",
            value: "",
          },
          type: "List",
        },
        classes: [],
      },
      outputs: [
        {
          id: "unclustered",
          key: "unclustered",
          type: "List",
        },
      ],
    },
  } as any,
  ocrAgent: {
    id: "f7a8b9c0-1d2e-4f3a-5b6c-7d8e9f0a1b2c",
    type: "agent",
    data: {
      type: "agent",
      name: "ocrAgent",
      title: "OCR",
      subtitle: "Extracts text from PDF files using OCR",
      description: "OCR Converts images and documents to text",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        value: {
          label: "",
          value: "",
        },
        provider_config: {
          provider: "",
          api_key: "",
          endpoint_url: "",
          model_id: "",
          pages: "",
          reading_order: "left-to-right",
          language: "eng",
        },
      },
      outputs: [
        {
          id: "text",
          key: "Text",
          type: "String",
          description: "Extracted Text",
        },
        {
          id: "confidence",
          key: "Confidence",
          type: "Number",
          description: "If supported by selected provider",
        },
        {
          id: "bounding_boxes",
          key: "Bounding_boxes",
          type: "String",
          description: "Per-region boxes & confidences",
        },
        // {
        //   id: "provider",
        //   key: "Provider",
        //   type: "String",
        //   description: 'tesseract", or "azure", "google", etc.',
        // },
        {
          id: "raw_response",
          key: "Raw_response",
          type: "String",
          description: "Original provider response",
        },
        {
          id: "pages",
          key: "Pages",
          type: "List of Strings",
          description: "List of pages with text content",
        },
      ],
    },
  },
  // formattingAgent: {
  //   id: "a8b9c0d1-2e3f-4a5b-6c7d-8e9f0a1b2c3d",
  //   type: "agent",
  //   data: {
  //     type: "agent",
  //     name: "formattingAgent",
  //     title: "Formatting Agent",
  //     subtitle: "Formats the input data into the specified data scheme",
  //     description: "",
  //     label: "",
  //     save_result: false,
  //     after_node_execution: "continue",
  //     inputs: [],
  //     outputs: [],
  //   },
  // } as any,
  llmAgent: {
    id: "c0d1e2f3-4a5b-6c7d-8e9f-0a1b2c3d4e5f",
    type: "agent",
    data: {
      type: "agent",
      name: "llmAgent",
      title: "LLM Agent",
      subtitle: "interacting with large language models using specified model providers",
      description: "LLM AI for writing and analysis",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        messages: [],
        system_prompt: "",
        model_parameters: {
          model: "gpt-4.1",
          provider: "azure",
          hyperparameters: {
            temperature: 0.7,
            max_tokens: 1000,
            top_p: 1,
            frequency_penalty: 0,
            presence_penalty: 0,
          },
        },
      },
      outputs: [
        {
          id: "tokens",
          type: "String",
          description: "The usage of tokens for each execution",
          required: false,
          key: "Tokens",
          readOnly: true,
        },
      ],
    },
  },
  deduplicationAgent: {
    id: "d1e2f3a4-5b6c-7d8e-9f0a-1b2c3d4e5f6b",
    type: "agent",
    data: {
      type: "agent",
      name: "deduplicationAgent",
      title: "Deduplication Agent",
      subtitle: "Removes duplicate entries from the input data",
      description: "Deduplication Detect and remove duplicate PDFs",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        items: {
          id: "items",
          key: "items",
          type: "List",
          value: {
            label: "",
            value: "",
          },
        },
        threshold: 95,
        keep_one_duplicate: true,
      },
      outputs: [
        {
          id: "unique",
          key: "Unique",
          type: "List",
          description: "List of unique entries after deduplication",
        },
        {
          id: "duplicates",
          key: "Duplicates",
          type: "List",
          description: "List of duplicate entries found",
        },
      ],
    },
  },
  customCodeAgent: {
    id: "d1e2f3a4-5b6c-7d8e-9f0a-1b2c3d4e5f6a",
    type: "agent",
    data: {
      type: "agent",
      name: "customCodeAgent",
      title: "Custom Code Agent",
      subtitle: "Handles custom code execution",
      description: "Code-Run custom Python logic safely",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        input_vars: [],
        code: "",
        language: "python",
        dependencies: [],
      },
      outputs: [],
    },
  },
  genOrModel: {
    id: "e8f9a0b1-2c3d-4e5f-6a7b-8c9d0e1f2a3b",
    type: "agent",
    data: {
      type: "agent",
      name: "genOrModel",
      title: "Action Models",
      subtitle: "Generative Orchestration Model",
      description: "Action Models Access and run Action models",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        model_inputs: [
          {
            id: "0",
            key: "Text",
            type: "Dictionary",
            description: "Expected input description",
            value: {
              label: "",
              value: "",
            },
          },
        ],
        init_kwargs: "",
        call_kwargs: "",
        model_id: "",
      },
      outputs: [
        {
          id: "output",
          key: "Text",
          type: "Dictionary",
          description: "Expected input description",
        },
      ],
    },
  },
  iterator: {
    id: "e2f3a4b5-6c7d-8e9f-0a1b-2c3d4e5f6a7b",
    type: "iterator",
    data: {
      type: "iterator",
      name: "iterator",
      title: "Iterator",
      subtitle: "Iterates over a dataset",
      description: "Iterator Process items one by one",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        iterable: null,
        max_iterations: 50,
        type: "while",
      },
      outputs: [
        {
          id: "raw_response",
          key: "raw_response",
          type: "Object",
          description: "Description",
          sourceNodeId: "",
        },
      ],
      variables: [],
    },
  },
  aggregator: {
    id: "f3a4b5c6-7d8e-9f0a-1b2c-3d4e5f6a7b8c",
    type: "aggregator",
    data: {
      type: "aggregator",
      name: "aggregator",
      title: "Aggregator",
      subtitle: "Aggregates results from multiple inputs",
      description: "Aggregator Merge multiple inputs into one",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: [],
      outputs: [],
    },
  },
  ifelse: {
    id: "a3d4e5f6-7b8c-4d9e-8f7a-1b2c3d4e5f6a",
    type: "ifelse",
    data: {
      name: "ifelse",
      type: "ifelse",
      title: "If Else",
      subtitle: "Conditional logic Operator",
      description: "If/Else Conditional branching",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: [],
      outputs: [],
      conditions: [
        {
          id: "if",
          type: "if",
          then: [],
          values: [],
        },
        {
          id: "else",
          type: "else",
          then: [],
          values: [],
        },
      ],
    },
  },
  filterAgent: {
    id: "b2c3d4e5-f6a7-4b8c-9d0a-1b2c3d4e5f6c",
    type: "agent",
    data: {
      name: "filterAgent",
      type: "agent",
      title: "Filter Agent",
      subtitle: "Filters input data based on specified conditions",
      description: "Filter Agent - Filter data based on conditions",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        iterable: {
          id: "2049d78b-55a0-41aa-aed7-5d9eddace717",
          key: "iterable",
          value: {
            label: "",
            value: "",
          },
          type: "List",
        },
        conditions: [],
      },
      outputs: [
        {
          id: "filtered_iterable",
          key: "filtered_iterable",
          type: "List",
          description: "List of items that meet the filter conditions",
        },
        {
          id: "original_count",
          key: "original_count",
          type: "Number",
          description: "Count of items before filtering",
        },
        {
          id: "filtered_count",
          key: "filtered_count",
          type: "Number",
          description: "Count of items after filtering",
        },
        {
          id: "filtered_indices",
          key: "filtered_indices",
          type: "List",
          description: "Indices of items that were removed during filtering",
        },
      ],
    },
  },
  APIAgent: {
    id: "a4b5c6d7-8e9f-0a1b-2c3d-4e5f6a7b8c9d",
    type: "agent",
    data: {
      type: "agent",
      name: "APIAgent",
      title: "API Agent",
      subtitle: "Fetches data from the specified API endpoint",
      description: "API Connect and call external APIs",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        url: "",
        method: "GET",
        headers: [],
        params: [],
        language: "python",
        data: "",
      },
      outputs: [
        {
          id: "data",
          key: "data",
          type: "Dictionary",
          description: "Parsed response body",
        },
        {
          id: "status",
          key: "status",
          type: "Integer",
          description: "HTTP status code",
        },
        {
          id: "headers",
          key: "headers",
          type: "Dictionary",
          description: "Response headers",
        },
      ],
    },
  },
  // VITClassifier: {
  //   id: "c6d7e8f9-0a1b-2c3d-4e5f-6a7b8c9d0e1f",
  //   type: "agent",
  //   data: {
  //     type: "agent",
  //     name: "VITClassifier",
  //     title: "VIT Classifier",
  //     subtitle: "A transformer-based image classification agent",
  //     description: "",
  //     label: "",
  //     save_result: false,
  //     after_node_execution: "continue",
  //     inputs: [],
  //     outputs: [],
  //   },
  // } as any,
  // YOLOAgent: {
  //   id: "d7e8f9a0-1b2c-3d4e-5f6a-7b8c9d0e1f2a",
  //   type: "agent",
  //   data: {
  //     type: "agent",
  //     name: "YOLOAgent",
  //     title: "YOLO Agent",
  //     subtitle: "Enables object detection and classification using Ultralytics YOLO",
  //     description: "",
  //     label: "",
  //     save_result: false,
  //     after_node_execution: "continue",
  //     inputs: [],
  //     outputs: [],
  //   },
  // } as any,
  dataLoader: {
    id: "d7e8f9a0-1b2c-3d4e-5f6a-7b8c9d0e1f2z",
    type: "dataLoader",
    data: {
      type: "dataLoader",
      name: "dataLoader",
      title: "Data Loader",
      subtitle: "Defines initial inputs",
      description: "",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: [
        {
          id: "0",
          key: "",
          type: {
            label: "File",
            value: "File",
          },
          value: {
            label: "",
            value: "",
          },
        },
      ],
      outputs: [
        {
          id: "0",
          key: "",
          type: "File",
        },
      ],
    },
  },
  splitterAgent: {
    id: "03028fd7-3d18-4a67-86ed-90d779471532",
    type: "agent",
    data: {
      name: "splitterAgent",
      type: "agent",
      title: "Splitter Agent",
      subtitle: "Splits input data into smaller chunks",
      description: "Splitter Convert PDF pages into images",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: {
        pdf_url: {
          id: "pdf_url",
          key: "pdf_url",
          type: "File",
          description: "The input file to be split",
          value: {
            label: "",
            value: "",
          },
        },
        dpi: 300,
        output_format: "PNG",
      },
      outputs: [
        {
          id: "images",
          key: "images",
          type: "List of Files",
          description: "List of image files after splitting",
        },
      ],
    },
  },
  subflow: {
    id: "asd",
    type: "subflow",
    data: {
      type: "subflow",
      name: "subflow",
      title: "Subflow",
      subtitle: "Reusable subflow",
      description: "",
      label: "",
      subflowConfigId: "",
      subflowId: "",
      after_node_execution: "continue",
      inputs: [],
      outputs: [],
    },
  },
  outlook: {
    id: "outlook-connector-id",
    type: "connector",
    data: {
      type: "connector",
      name: "outlook",
      title: "Outlook",
      subtitle: "Connects to an email account to monitor for new messages and extract attachments.",
      description: "",
      subtype: "email",
      label: "",
      save_result: false,
      after_node_execution: "continue",
      inputs: [
        {
          id: "subject_001",
          key: "subject",
          type: "String",
          value: {
            label: "Email Subject",
            value: "",
          },
          description: "Subject line of the email",
        },
        {
          id: "userId_001",
          key: "userId",
          type: "String",
          value: {
            label: "",
            value: "",
          },
          description: "active account user ID",
        },
        {
          id: "body_001",
          key: "body",
          type: "String",
          value: {
            label: "Email Body",
            value: "",
          },
          description: "Main content of the email",
        },
        {
          id: "to_001",
          key: "to",
          type: "List of Strings",
          value: {
            label: "Recipients",
            value: [],
          },
          description: "Primary recipients email addresses",
        },
        {
          id: "toName_001",
          key: "toName",
          type: "List of Strings",
          value: {
            label: "Recipient Names",
            value: [],
          },
          description: "Display names for primary recipients",
        },
        {
          id: "cc_001",
          key: "cc",
          type: "List of Strings",
          value: {
            label: "CC Recipients",
            value: [],
          },
          description: "Carbon copy recipients",
        },
        {
          id: "bcc_001",
          key: "bcc",
          type: "List of Strings",
          value: {
            label: "BCC Recipients",
            value: [],
          },
          description: "Blind carbon copy recipients",
        },
        {
          id: "attachments_001",
          key: "attachments",
          type: "List of Strings",
          value: {
            label: "Attachments",
            value: [],
          },
          description: "File paths or names of attachments",
        },
        {
          id: "referencedAttachments_001",
          key: "referencedAttachments",
          type: "List of Strings",
          value: {
            label: "Referenced Attachments",
            value: [],
            isReference: true,
          },
          description: "File paths or names of attachments",
        },
        {
          id: "sendDate_001",
          key: "sendDate",
          type: "String",
          value: {
            label: "Send Date",
            value: "",
          },
          description: "Date to send the email (YYYY-MM-DD format)",
        },
        {
          id: "sendTime_001",
          key: "sendTime",
          type: "String",
          value: {
            label: "Send Time",
            value: "",
          },
          description: "Time to send the email (HH:MM format)",
        },
        {
          id: "outlookSignature_001",
          key: "outlookSignature",
          type: "Boolean",
          value: {
            label: "Include Outlook Signature",
            value: false,
          },
          description: "Whether to include the default Outlook signature",
        },
        {
          id: "action_001",
          key: "action",
          type: "String",
          value: {
            label: "Action Type",
            value: "SEND",
          },
          description: "Action to perform (SEND, DRAFT, SCHEDULE)",
        },
        {
          id: "messageStatus_001",
          key: "messageStatus",
          type: "String",
          value: {
            label: "Message Status",
            value: "all",
          },
          description: "Filter for message status",
        },
        {
          id: "dateFrom_001",
          key: "dateFrom",
          type: "String",
          value: {
            label: "Date From",
            value: "",
          },
          description: "Start date for filtering messages (YYYY-MM-DD format)",
        },
        {
          id: "dateTo_001",
          key: "dateTo",
          type: "String",
          value: {
            label: "Date To",
            value: "",
          },
          description: "End date for filtering messages (YYYY-MM-DD format)",
        },
        {
          id: "filterTo_001",
          key: "filterTo",
          type: "String",
          value: {
            label: "Filter To",
            value: "",
          },
          description: "Folder to filter messages from",
        },
        {
          id: "bodyContains_001",
          key: "bodyContains",
          type: "String",
          value: {
            label: "Body Contains",
            value: "",
          },
          description: "Keyword to search for in the email body",
        },
        {
          id: "hasAttachments_001",
          key: "hasAttachments",
          type: "String",
          value: {
            label: "Has Attachments",
            value: "Both",
          },
          description: "Filter for emails with attachments",
        },
        {
          id: "allowedFileTypes_001",
          key: "allowedFileTypes",
          type: "String",
          value: {
            label: "Allowed File Types",
            value: "",
          },
          description: "File types allowed for attachments",
        },
        {
          id: "minSizeMB_001",
          key: "minSizeMB",
          type: "Number",
          value: {
            label: "Minimum Size (MB)",
            value: 0,
          },
          description: "Minimum size of attachments in MB",
        },
        {
          id: "maxSizeMB_001",
          key: "maxSizeMB",
          type: "Number",
          value: {
            label: "Maximum Size (MB)",
            value: 10,
          },
          description: "Maximum size of attachments in MB",
        },
        {
          id: "maxEmailsToReturn_001",
          key: "maxEmailsToReturn",
          type: "Number",
          value: {
            label: "Max Emails to Return",
            value: 100,
          },
          description: "Maximum number of emails to return",
        },
        {
          id: "includeSubfolders_001",
          key: "includeSubfolders",
          type: "Boolean",
          value: {
            label: "Include Subfolders",
            value: true,
          },
          description: "Whether to include subfolders in the search",
        },
        {
          id: "markAsReadAfterProcessing_001",
          key: "markAsReadAfterProcessing",
          type: "Boolean",
          value: {
            label: "Mark as Read After Processing",
            value: true,
          },
          description: "Whether to mark emails as read after processing",
        },
        {
          id: "folders_001",
          key: "folders",
          type: "List of Strings",
          value: {
            label: "Folders",
            value: [],
          },
          description: "Folders to search in",
        },
        {
          id: "from_001",
          key: "from",
          type: "List of Strings",
          value: {
            label: "Sender Emails",
            value: [],
          },
          description: "Filter by sender email addresses",
        },
        {
          id: "subjectContains_001",
          key: "subjectContains",
          type: "String",
          value: {
            label: "Subject Contains",
            value: "",
          },
          description: "Keyword(s) to search for in the email subject",
        },
      ],
      outputs: [
        {
          id: "success",
          key: "success",
          type: "Boolean",
          description: "Whether the operation was successful",
        },
        {
          id: "message_id",
          key: "message",
          type: "String",
          description: "ID of the sent message",
        },
      ],
    },
  },
  slack: {
    id: "slack-connector-id",
    type: "connector",
    data: {
      type: "connector",
      name: "slack",
      title: "Slack",
      subtitle: "Integrates with Slack messaging",
      description: "Connect and interact with Slack workspace",
      label: "",
      save_result: false,
      connectorId: "",
      after_node_execution: "continue",
      inputs: [
        {
          id: "0",
          key: "channel",
          type: "String",
          value: {
            label: "Channel",
            value: "",
          },
          description: "Slack channel or user ID",
        },
        {
          id: "1",
          key: "message",
          type: "String",
          value: {
            label: "Message",
            value: "",
          },
          description: "Message content to send",
        },
        {
          id: "2",
          key: "thread_ts",
          type: "String",
          value: {
            label: "Thread Timestamp",
            value: "",
          },
          description: "Thread timestamp for replies (optional)",
        },
      ],
      outputs: [
        {
          id: "success",
          key: "Success",
          type: "Boolean",
          description: "Whether the message was sent successfully",
        },
        {
          id: "timestamp",
          key: "Timestamp",
          type: "String",
          description: "Message timestamp",
        },
        {
          id: "channel_id",
          key: "Channel ID",
          type: "String",
          description: "ID of the channel where message was sent",
        },
      ],
    },
  },
  zoom: {
    id: "zoom-connector-id",
    type: "connector",
    data: {
      type: "connector",
      name: "zoom",
      title: "Zoom",
      subtitle: "Integrates with Zoom meetings",
      description: "Connect and interact with Zoom video conferencing",
      label: "",
      save_result: false,
      connectorId: "",
      after_node_execution: "continue",
      inputs: [
        {
          id: "0",
          key: "meeting_title",
          type: "String",
          value: {
            label: "Meeting Title",
            value: "",
          },
          description: "Title of the Zoom meeting",
        },
        {
          id: "1",
          key: "start_time",
          type: "String",
          value: {
            label: "Start Time",
            value: "",
          },
          description: "Meeting start time (ISO 8601 format)",
        },
        {
          id: "2",
          key: "duration",
          type: "Number",
          value: {
            label: "Duration",
            value: "60",
          },
          description: "Meeting duration in minutes",
        },
        {
          id: "3",
          key: "attendees",
          type: "List of Strings",
          value: {
            label: "Attendees",
            value: "",
          },
          description: "List of attendee email addresses",
        },
      ],
      outputs: [
        {
          id: "meeting_id",
          key: "Meeting ID",
          type: "String",
          description: "Unique meeting identifier",
        },
        {
          id: "join_url",
          key: "Join URL",
          type: "String",
          description: "Meeting join URL",
        },
        {
          id: "start_url",
          key: "Start URL",
          type: "String",
          description: "Host start URL",
        },
        {
          id: "password",
          key: "Password",
          type: "String",
          description: "Meeting password",
        },
      ],
    },
  },
} satisfies FlowConfiguration;
