import { Monaco } from "@monaco-editor/react";

export const refreshTheme = (monaco: Monaco, currentTheme: "dark" | "light") => {
  const style = window.getComputedStyle(document.documentElement);

  monaco.editor.defineTheme("custom-theme", {
    base: currentTheme === "dark" ? "vs-dark" : "vs",
    inherit: true,
    rules: [
      {
        token: "",
        foreground: `${style.getPropertyValue("--code-default").trim()}`,
        background: `${style.getPropertyValue("--code-background").trim()}`,
      },
      { token: "invalid", foreground: `${style.getPropertyValue("--code-invalid").trim()}` },
      { token: "emphasis", fontStyle: "italic" },
      { token: "strong", fontStyle: "bold" },
      { token: "variable", foreground: `${style.getPropertyValue("--code-variable").trim()}` },
      { token: "variable.predefined", foreground: `${style.getPropertyValue("--code-variable-predefined").trim()}` },
      { token: "variable.parameter", foreground: `${style.getPropertyValue("--code-variable-parameter").trim()}` },
      { token: "constant", foreground: `${style.getPropertyValue("--code-constant").trim()}` },
      { token: "comment", foreground: `${style.getPropertyValue("--code-comment").trim()}` },
      { token: "number", foreground: `${style.getPropertyValue("--code-number").trim()}` },
      { token: "number.hex", foreground: `${style.getPropertyValue("--code-number-hex").trim()}` },
      { token: "regexp", foreground: `${style.getPropertyValue("--code-regexp").trim()}` },
      { token: "annotation", foreground: `${style.getPropertyValue("--code-annotation").trim()}` },
      { token: "type", foreground: `${style.getPropertyValue("--code-type").trim()}` },
      { token: "delimiter", foreground: `${style.getPropertyValue("--code-delimiter").trim()}` },
      { token: "delimiter.html", foreground: `${style.getPropertyValue("--code-delimiter-html").trim()}` },
      { token: "delimiter.xml", foreground: `${style.getPropertyValue("--code-delimiter-xml").trim()}` },
      { token: "tag", foreground: `${style.getPropertyValue("--code-tag").trim()}` },
      { token: "tag.id.pug", foreground: `${style.getPropertyValue("--code-tag-id-pug").trim()}` },
      { token: "tag.class.pug", foreground: `${style.getPropertyValue("--code-tag-class-pug").trim()}` },
      { token: "meta.scss", foreground: `${style.getPropertyValue("--code-meta-scss").trim()}` },
      { token: "meta.tag", foreground: `${style.getPropertyValue("--code-meta-tag").trim()}` },
      { token: "metatag", foreground: `${style.getPropertyValue("--code-metatag").trim()}` },
      { token: "metatag.content.html", foreground: `${style.getPropertyValue("--code-metatag-content-html").trim()}` },
      { token: "metatag.html", foreground: `${style.getPropertyValue("--code-metatag-html").trim()}` },
      { token: "metatag.xml", foreground: `${style.getPropertyValue("--code-metatag-xml").trim()}` },
      { token: "metatag.php", fontStyle: "bold" },
      { token: "key", foreground: `${style.getPropertyValue("--code-key").trim()}` },
      { token: "string.key.json", foreground: `${style.getPropertyValue("--code-string-key-json").trim()}` },
      { token: "string.value.json", foreground: `${style.getPropertyValue("--code-string-value-json").trim()}` },
      { token: "attribute.name", foreground: `${style.getPropertyValue("--code-attribute-name").trim()}` },
      { token: "attribute.value", foreground: `${style.getPropertyValue("--code-attribute-value").trim()}` },
      { token: "attribute.value.number.css", foreground: `${style.getPropertyValue("--code-attribute-value-number-css").trim()}` },
      { token: "attribute.value.unit.css", foreground: `${style.getPropertyValue("--code-attribute-value-unit-css").trim()}` },
      { token: "attribute.value.hex.css", foreground: `${style.getPropertyValue("--code-attribute-value-hex-css").trim()}` },
      { token: "string", foreground: `${style.getPropertyValue("--code-string").trim()}` },
      { token: "string.sql", foreground: `${style.getPropertyValue("--code-string-sql").trim()}` },
      { token: "keyword", foreground: `${style.getPropertyValue("--code-keyword").trim()}` },
      { token: "keyword.flow", foreground: `${style.getPropertyValue("--code-keyword-flow").trim()}` },
      { token: "keyword.json", foreground: `${style.getPropertyValue("--code-keyword-json").trim()}` },
      { token: "keyword.flow.scss", foreground: `${style.getPropertyValue("--code-keyword-flow-scss").trim()}` },
      { token: "operator.scss", foreground: `${style.getPropertyValue("--code-operator-scss").trim()}` },
      { token: "operator.sql", foreground: `${style.getPropertyValue("--code-operator-sql").trim()}` },
      { token: "operator.swift", foreground: `${style.getPropertyValue("--code-operator-swift").trim()}` },
      { token: "predefined.sql", foreground: `${style.getPropertyValue("--code-predefined-sql").trim()}` },
    ],
    colors: {
      "editor.background": `#${style.getPropertyValue("--code-background").trim()}`,
      "editor.foreground": `#${style.getPropertyValue("--code-foreground").trim()}`,
      "editor.inactiveSelectionBackground": `#${style.getPropertyValue("--code-inactive-selection-bg").trim()}`,
      "editorIndentGuide.background1": `#${style.getPropertyValue("--code-indent-guide-bg").trim()}`,
      "editorIndentGuide.activeBackground1": `#${style.getPropertyValue("--code-indent-guide-active-bg").trim()}`,
      "editor.selectionHighlightBackground": `#${style.getPropertyValue("--code-selection-highlight-bg").trim()}`,
    },
  });
  monaco.editor.setTheme("custom-theme");
};
